version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket 6998hw2-lambda-pipeline-bucket --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputsamtemplate.yml
