AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Photo Album Lambda
Resources:
  IndexPhotosLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos
      Handler: index-photos.lambda_handler
      Runtime: python3.9
      CodeUri: ./index-photos.py
      Description: 'index-photos Lambda function for Photo Album'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::261903827858:role/service-role/6998hw2-LF1-role-2qrhedw9'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
  SearchPhotosLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos
      Handler: search-photos.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos.py
      Description: 'search-photos Lambda function for Photo Album'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::261903827858:role/service-role/search-photos-role-bfdiy8sg'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1